name: Coveralls

on: [push, pull_request]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coveralls:
    if: github.repository_owner == 'hazendaz'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
        with:
          cache: maven
          distribution: temurin
          java-version: 25
      - name: Run the build and install to m2
        run: ./mvnw install --batch-mode --no-transfer-progress --quiet --show-version -Dlicense.skip=true
      - name: Report Coverage to Coveralls for Pull Requests
        if: github.event_name == 'pull_request'
        run: ./mvnw generate-sources jacoco:report coveralls:report --batch-mode --no-transfer-progress -DpullRequest=${{ env.PR_NUMBER }} -DrepoToken=${{ env.GITHUB_TOKEN }} -DserviceName=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
      - name: Get Coveralls Maven Plugin Version
        id: get_version
        run: echo "PLUGIN_VERSION=$(./mvnw help:evaluate --quiet -Dexpression=project.version -DforceStdout)" >> $GITHUB_ENV
      - name: Report Coverage to Coveralls for General Push using current snapshot version
        if: github.event_name == 'push'
        run: ./mvnw generate-sources jacoco:report coveralls:report --batch-mode --no-transfer-progress -Dcoveralls.plugin=${{ env.PLUGIN_VERSION }} -DrepoToken=${{ env.GITHUB_TOKEN }} -DserviceName=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
